### ISSUE TITLE
Crear el modelo de entidades

### ISSUE THREAD

**Issue by julimo21** [julimo21/Minuta#1]

**Comment by julimo21** [comment]
Se adjunta imagen con el modelo de entidades propuesto para el proyecto: Minuta de vigilancia.

![Image](https://user-images.githubusercontent.com/111019132/186508865-35707022-5720-494e-94ab-a6f7957e8e71.JPG)

**Comment by julimo21** [comment]
Se adicionó al modelo de entidades, las clases Persona, Visitante, Vigilante, Administrador, Residente, Usuarios y TipoUsuarios.

Adjunto modelo de entidades:


![Image](https://user-images.githubusercontent.com/111019132/186989399-2429c83c-1278-4ee6-a29b-eb12d7acfc3a.JPG)

**Comment by njzapatam** [comment]
Se adjunta el modelo establecido a partir de la reunión con el tutor, pendiente a reunión para definir si se consolida como el modelo definitivo.



![Image](https://user-images.githubusercontent.com/111405593/187046392-bb834475-e61e-4a0b-b8bb-8cd82187df24.png)

**Comment by njzapatam** [comment]
Se adjunta el versión 3 del modelo de entidades, con ajustes de la reunión del lunes 29/08/2022 y lo definido en la clase del martes 30/08/2022.



![Image](https://user-images.githubusercontent.com/111405593/187469218-9acd1c0a-f123-4b4c-976f-7ef7bd687070.png)
