### ISSUE TITLE
Requerimientos del proyecto

### ISSUE THREAD

**Issue by julimo21** [julimo21/Minuta#12]

**Comment by julimo21** [comment]
![Image](https://user-images.githubusercontent.com/111019132/186255948-f91ca54a-c70f-4de3-bd58-e3de4c9927c3.JPG)

Estamos a la espera de la definición final de requerimientos mañana miércoles 24 de Agosto de 2022.

**Comment by njzapatam** [comment]
Se adjuntan los requerimientos finales definidos por el stakeholder (profesor) y los desarrolladores.



![Image](https://user-images.githubusercontent.com/111405593/186508604-de06cb47-0e73-4400-8019-6cbce748de83.png)



[REQUERIMIENTOS 1.pdf](https://github.com/julimo21/Minuta/files/9418892/REQUERIMIENTOS.1.pdf)

**Comment by JejanSystem** [comment]
Se indica que se creara subcarpetas  dentro de la carpeta  **Proyecto minuta de vigilancia** con el fin de  facilitar el acceso a determinada linea de código según la capa a la cual pertenezca.

**Comment by JejanSystem** [comment]
Se crea subcarpetas: requerimientos, modelo entidades, minuta app, formato informes de seguimiento.
