### ISSUE TITLE
Definir lineamientos para el código (estándares del equipo)

### ISSUE THREAD

**Issue by julimo21** [julimo21/Minuta#4]

**Comment by alvar2810** [comment]
1. Las entidades su nombre iniciaran con letra mayuscula, la primera (1).
2. Los atributos se escribiran con letra minuscula, para diferenciarlas..
3. Las clases llevaran el mismo nombre de la identidad correspondiente.
4. la nomenclatura de la escritura del codigo, usara la convencion camelCase.
5. Las llaves se escibiran en una linea vacia, aparte...
6. El proyecto llevara cada una de las capas (dominio,persistencia,servicios,sln)
