### ISSUE TITLE
Explorar   herramientas para prototipos de UI (https://www.lucidchart.com/pages/)

### ISSUE THREAD

**Issue by julimo21** [julimo21/Minuta#8]

**Comment by njzapatam** [comment]
Se han hecho los siguientes hallazgos para la creación de la UI:

1. La página LucidChart tiene un template para el login y acceso con contraseña, al cual se puede acceder con el siguiente link: [LucidChart](https://www.lucidchart.com/pages/es/plantillas/ejemplo-de-flujo-de-tareas-de-restablecimiento-de-contrasena?gclid=CjwKCAjwmJeYBhAwEiwAXlg0AcWP6a_XZBZ5qphFUOdgLaZ2mCO8YJl0NSlvEc-q7x3kFj1n4P-9GBoCeh8QAvD_BwE&km_CPC_AdGroupID=63362176052&km_CPC_AdPosition=&km_CPC_CampaignId=1501207859&km_CPC_Country=1029279&km_CPC_Creative=286841060369&km_CPC_Device=c&km_CPC_ExtensionID=&km_CPC_Keyword=lucidchart&km_CPC_MatchType=e&km_CPC_Network=g&km_CPC_TargetID=aud-1660700197412%3Akwd-33511936169&km_CPC_placement=&km_CPC_target=&utm_campaign=_chart_es_tier2_mixed_search_brand_exact_&utm_medium=cpc&utm_source=google)

2. Existe una herramienta interactiva llamada UIWizard, al cual se puede acceder a través de la siguiente dirección: [UIWizard](https://app.uizard.io/prototypes)

**Comment by njzapatam** [comment]
3. El programa Justinmind permite la creación de prototipos a través de una aplicación altamente interactiva que se puede obtener en el siguiente hipervínculo: [Justinmind](https://www.justinmind.com/)
