### ISSUE TITLE
Hacer listado de pruebas básicas para el siguiente sprint

### ISSUE THREAD

**Issue by julimo21** [julimo21/Minuta#9]

**Comment by JhojanRendon** [comment]
Se ha definido que para el primer sprint se harán las siguientes pruebas para verificar la calidad y eficiencia del mismo:

PRUEBA 1- Comprobar que las clases y que todo lo que compone al código no contenga errores de sintaxis o de otro tipo. Esta prueba se hará a través de una compilación ejecutada desde la terminal con ayuda del comando dotnet build.

PRUEBA 2- Realizar la migración del código a una base de datos a través del comando definido para tal fin y comprobar que la migración a la base de datos a sido exitosa. 

PRUEBA 3- Se verifica y se comprueba en el administrador de bases de datos si se generan las tablas esperadas.
